const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const path = process.argv[2] || 'C:/Users/z/AppData/Roaming/io.github.clash-verge-rev.clash-verge-rev/profiles/Script.js';
const ctx = {}; vm.createContext(ctx); vm.runInContext(fs.readFileSync(path, 'utf8'), ctx);
const fixture = () => ({mode:'rule', 'mixed-port':7897, proxies:['日本1','日本2','美国1','美国2 gemini','香港1','剩余流量：99GB'].map(name=>({name,type:'trojan',server:'example.test',port:443})), 'proxy-groups':[{name:'主选择',type:'select',proxies:['故障转移','日本1']},{name:'故障转移',type:'fallback',interval:7200,proxies:['剩余流量：99GB','日本1','美国1']}],rules:['MATCH,主选择']});
let out=ctx.main(fixture());
const jp=out['proxy-groups'].find(g=>g.name==='🇯🇵 日本｜日常高速');
assert(jp, 'missing daily Japan group');
assert.equal(jp.type,'url-test');
assert(jp.proxies.every(n=>n.includes('日本')));
const us=out['proxy-groups'].find(g=>g.name==='🇺🇸 美国｜反重力候选');
assert(us && us.proxies.every(n=>n.includes('美国')));
assert.equal(out.proxies.length,5,'must not inject hardcoded nodes or placeholders');
assert(!out['proxy-groups'].some(g=>(g.proxies||[]).some(n=>n.includes('剩余流量'))));
assert.equal(out.mode,'rule'); assert.equal(out['mixed-port'],7897);
assert(out.rules.includes('MATCH,主选择'));
assert.equal(JSON.stringify(ctx.main(JSON.parse(JSON.stringify(out)))),JSON.stringify(out),'idempotence');
const noUS=fixture(); noUS.proxies=noUS.proxies.filter(p=>!p.name.includes('美国'));
assert(!ctx.main(noUS)['proxy-groups'].some(g=>g.name==='🇺🇸 美国｜反重力候选'),'no fake US fallback');
console.log('purpose_groups_pass');
const refreshed=fixture();
refreshed.proxies=refreshed.proxies.filter(p=>p.name!=='日本2');
refreshed.proxies.find(p=>p.name==='日本1').server='new-endpoint.example.test';
refreshed.proxies.push({name:'美国3',type:'trojan',server:'new-us.example.test',port:8443});
const updated=ctx.main(refreshed);
assert(!updated['proxy-groups'].find(g=>g.name===jp.name).proxies.includes('日本2'));
assert(updated['proxy-groups'].find(g=>g.name===us.name).proxies.includes('美国3'));
assert.equal(updated.proxies.find(p=>p.name==='日本1').server,'new-endpoint.example.test');
console.log('subscription_replacement_pass');
